#Configuracion para la base de datos 

default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000



development:
  <<: *default
  database: db/development.sqlite3

# Test sirve para testear
test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>